### ISSUE TITLE
Hii bro 

### ISSUE THREAD

**Issue by 9596imran** [LEGEND-OS/LEGENDBOT#5]
I am imran @amimran786 from telegram just want to now why u deleted account and also bot os not working 😢

**Comment by LEGEND-OS** [comment]
Yoh

**Comment by 9596imran** [comment]
Bro I need your help

**Comment by 9596imran** [comment]
Created a blog but don't know how and whta to doo

**Comment by LEGEND-OS** [comment]
do u use telegram

**Comment by 9596imran** [comment]
Yes bro

**Comment by 9596imran** [comment]
@amimran786

**Comment by LEGEND-OS** [comment]
come in telegram

**Comment by 9596imran** [comment]
> come in telegram

Id

**Comment by 9596imran** [comment]
Sharpshooter00000
Or
Cyclone

**Comment by 9596imran** [comment]
Bro reply yrr 😞

**Comment by 9596imran** [comment]
I know 😼 it's my own badness that I was being unable to modify my blog 😭

**Comment by 9596imran** [comment]
![Uploading Screenshot_2021-09-28-17-27-49-69_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by 9596imran** [comment]
![Screenshot_2021-09-28-17-27-49-69_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/83054591/135082488-8b50e1f0-bcfa-40a0-9e54-d7510c8fbbac.jpg)

**Comment by 9596imran** [comment]
I had dm you on instagram 😌

**Comment by LEGEND-OS** [comment]
i hope all done
